[project]
name = "finance-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "yfinance",
    "pandas",
    "requests",
    "numpy",
    "python-dateutil",
]
